#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = 'sims_2.2.4maf+1'
__repo_version__ = 'sims_2.2.4maf'
__repo_version__ = 'sims_2.2.4maf'
__fingerprint__ = '241fd8972f7debce39f1140daa5d5722da4accd1'
__rebuild_version__ = 1
__dependency_versions__ = {
}
__all__ = ('__version__', '__repo_version__', '__repo_version__', '__fingerprint__', '__rebuild_version__', '__dependency_versions__')
